// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyNutritionByRange = `-- name: GetDailyNutritionByRange :many
SELECT 
    DATE(fd.consumed_at)::date as date,
    COALESCE(SUM(
        f.serving_size * fd.amount_consumed / 100.0 * fn.amount
    ), 0)::float8 as total_calories,
    COALESCE(SUM(
        CASE WHEN n."name" = 'Protein' 
        THEN f.serving_size * fd.amount_consumed / 100.0 * fn.amount 
        ELSE 0 END
    ), 0)::float8 as protein,
    COALESCE(SUM(
        CASE WHEN n."name" = 'Carbs' 
        THEN f.serving_size * fd.amount_consumed / 100.0 * fn.amount 
        ELSE 0 END
    ), 0)::float8 as carbs,
    COALESCE(SUM(
        CASE WHEN n."name" = 'Fat' 
        THEN f.serving_size * fd.amount_consumed / 100.0 * fn.amount 
        ELSE 0 END
    ), 0)::float8 as fat,
    COUNT(fd.id)::int as entry_count
FROM food_diaries fd
JOIN foods f ON fd.food_id = f.id
JOIN food_nutrients fn ON f.id = fn.food_id
JOIN nutrients n ON fn.nutrient_id = n.id
WHERE fd.user_id = $1 
    AND DATE(fd.consumed_at) >= $2 
    AND DATE(fd.consumed_at) <= $3
    AND fd.deleted_at IS NULL
GROUP BY DATE(fd.consumed_at)
ORDER BY date ASC
`

type GetDailyNutritionByRangeParams struct {
	UserID       int64              `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
}

type GetDailyNutritionByRangeRow struct {
	Date          time.Time `json:"date"`
	TotalCalories float64   `json:"total_calories"`
	Protein       float64   `json:"protein"`
	Carbs         float64   `json:"carbs"`
	Fat           float64   `json:"fat"`
	EntryCount    int32     `json:"entry_count"`
}

func (q *Queries) GetDailyNutritionByRange(ctx context.Context, arg GetDailyNutritionByRangeParams) ([]GetDailyNutritionByRangeRow, error) {
	rows, err := q.db.Query(ctx, getDailyNutritionByRange, arg.UserID, arg.ConsumedAt, arg.ConsumedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyNutritionByRangeRow
	for rows.Next() {
		var i GetDailyNutritionByRangeRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalCalories,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
