// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateNutritionLogsBatch implements pgx.CopyFromSource.
type iteratorForCreateNutritionLogsBatch struct {
	rows                 []CreateNutritionLogsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateNutritionLogsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateNutritionLogsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FoodName,
		r.rows[0].Calories,
		r.rows[0].ProteinG,
		r.rows[0].CarbsG,
		r.rows[0].FatG,
		r.rows[0].SugarG,
		r.rows[0].UserID,
		r.rows[0].ScanID,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForCreateNutritionLogsBatch) Err() error {
	return nil
}

func (q *Queries) CreateNutritionLogsBatch(ctx context.Context, arg []CreateNutritionLogsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"nutrition_logs"}, []string{"food_name", "calories", "protein_g", "carbs_g", "fat_g", "sugar_g", "user_id", "scan_id", "created_by"}, &iteratorForCreateNutritionLogsBatch{rows: arg})
}
