// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diary.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiaryEntry = `-- name: CreateDiaryEntry :one
INSERT INTO food_diaries (user_id, food_id, amount_consumed, consumed_at, meal_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at
`

type CreateDiaryEntryParams struct {
	UserID         int64              `json:"user_id"`
	FoodID         int64              `json:"food_id"`
	AmountConsumed pgtype.Numeric     `json:"amount_consumed"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	MealType       pgtype.Text        `json:"meal_type"`
}

type CreateDiaryEntryRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (CreateDiaryEntryRow, error) {
	row := q.db.QueryRow(ctx, createDiaryEntry,
		arg.UserID,
		arg.FoodID,
		arg.AmountConsumed,
		arg.ConsumedAt,
		arg.MealType,
	)
	var i CreateDiaryEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteDiaryEntry = `-- name: DeleteDiaryEntry :execrows
UPDATE food_diaries
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDiaryEntry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDiaryEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDiaryEntries = `-- name: GetDiaryEntries :many
SELECT
    fd.id,
    fd.amount_consumed,
    fd.consumed_at,
    fd.meal_type,
    fd.created_at,
    fd.updated_at,
    f.name as food_name
FROM food_diaries fd
JOIN foods f ON f.id = fd.food_id
WHERE fd.user_id = $1
  AND DATE(fd.consumed_at) = $2
  AND fd.deleted_at IS NULL
`

type GetDiaryEntriesParams struct {
	UserID     int64              `json:"user_id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type GetDiaryEntriesRow struct {
	ID             int64              `json:"id"`
	AmountConsumed pgtype.Numeric     `json:"amount_consumed"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	MealType       pgtype.Text        `json:"meal_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	FoodName       string             `json:"food_name"`
}

func (q *Queries) GetDiaryEntries(ctx context.Context, arg GetDiaryEntriesParams) ([]GetDiaryEntriesRow, error) {
	rows, err := q.db.Query(ctx, getDiaryEntries, arg.UserID, arg.ConsumedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiaryEntriesRow
	for rows.Next() {
		var i GetDiaryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountConsumed,
			&i.ConsumedAt,
			&i.MealType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FoodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryEntry = `-- name: GetDiaryEntry :one
SELECT
    fd.user_id,
    fd.food_id,
    fd.amount_consumed,
    fd.consumed_at,
    fd.meal_type,
    f.name as food_name,
    fd.created_at,
    fd.updated_at
FROM food_diaries fd
JOIN foods f ON fd.food_id = f.id
WHERE fd.id = $1 AND fd.deleted_at IS NULL
`

type GetDiaryEntryRow struct {
	UserID         int64              `json:"user_id"`
	FoodID         int64              `json:"food_id"`
	AmountConsumed pgtype.Numeric     `json:"amount_consumed"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	MealType       pgtype.Text        `json:"meal_type"`
	FoodName       string             `json:"food_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDiaryEntry(ctx context.Context, id int64) (GetDiaryEntryRow, error) {
	row := q.db.QueryRow(ctx, getDiaryEntry, id)
	var i GetDiaryEntryRow
	err := row.Scan(
		&i.UserID,
		&i.FoodID,
		&i.AmountConsumed,
		&i.ConsumedAt,
		&i.MealType,
		&i.FoodName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiarySummary = `-- name: GetDiarySummary :one
SELECT
    COALESCE(SUM(CASE WHEN n.name = 'Caloric Value' THEN (fd.amount_consumed / NULLIF(f.serving_size, 0)) * fn.amount END), 0)::float8 as total_calories,
    COALESCE(SUM(CASE WHEN n.name = 'Protein' THEN (fd.amount_consumed / NULLIF(f.serving_size, 0)) * fn.amount END), 0)::float8 as total_protein,
    COALESCE(SUM(CASE WHEN n.name = 'Carbohydrates' THEN (fd.amount_consumed / NULLIF(f.serving_size, 0)) * fn.amount END), 0)::float8 as total_carbs,
    COALESCE(SUM(CASE WHEN n.name = 'Fat' THEN (fd.amount_consumed / NULLIF(f.serving_size, 0)) * fn.amount END), 0)::float8 as total_fat
FROM food_diaries fd
JOIN foods f ON fd.food_id = f.id AND f.deleted_at IS NULL
JOIN food_nutrients fn ON f.id = fn.food_id
JOIN nutrients n ON fn.nutrient_id = n.id
WHERE fd.user_id = $1
    AND DATE(fd.consumed_at) = $2
    AND fd.deleted_at IS NULL
`

type GetDiarySummaryParams struct {
	UserID     int64              `json:"user_id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type GetDiarySummaryRow struct {
	TotalCalories float64 `json:"total_calories"`
	TotalProtein  float64 `json:"total_protein"`
	TotalCarbs    float64 `json:"total_carbs"`
	TotalFat      float64 `json:"total_fat"`
}

func (q *Queries) GetDiarySummary(ctx context.Context, arg GetDiarySummaryParams) (GetDiarySummaryRow, error) {
	row := q.db.QueryRow(ctx, getDiarySummary, arg.UserID, arg.ConsumedAt)
	var i GetDiarySummaryRow
	err := row.Scan(
		&i.TotalCalories,
		&i.TotalProtein,
		&i.TotalCarbs,
		&i.TotalFat,
	)
	return i, err
}

const getUserDiaryEntry = `-- name: GetUserDiaryEntry :one
SELECT
    fd.user_id,
    fd.food_id,
    fd.amount_consumed,
    fd.consumed_at,
    fd.meal_type,
    f.name as food_name,
    fd.created_at,
    fd.updated_at
FROM food_diaries fd
JOIN foods f ON fd.food_id = f.id
WHERE fd.id = $1 AND fd.user_id = $2 AND fd.deleted_at IS NULL
`

type GetUserDiaryEntryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetUserDiaryEntryRow struct {
	UserID         int64              `json:"user_id"`
	FoodID         int64              `json:"food_id"`
	AmountConsumed pgtype.Numeric     `json:"amount_consumed"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	MealType       pgtype.Text        `json:"meal_type"`
	FoodName       string             `json:"food_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserDiaryEntry(ctx context.Context, arg GetUserDiaryEntryParams) (GetUserDiaryEntryRow, error) {
	row := q.db.QueryRow(ctx, getUserDiaryEntry, arg.ID, arg.UserID)
	var i GetUserDiaryEntryRow
	err := row.Scan(
		&i.UserID,
		&i.FoodID,
		&i.AmountConsumed,
		&i.ConsumedAt,
		&i.MealType,
		&i.FoodName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDiaryEntry = `-- name: UpdateDiaryEntry :execrows
UPDATE food_diaries
SET
    food_id = $2,
    amount_consumed = $3,
    consumed_at = $4,
    meal_type = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDiaryEntryParams struct {
	ID             int64              `json:"id"`
	FoodID         int64              `json:"food_id"`
	AmountConsumed pgtype.Numeric     `json:"amount_consumed"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	MealType       pgtype.Text        `json:"meal_type"`
}

func (q *Queries) UpdateDiaryEntry(ctx context.Context, arg UpdateDiaryEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDiaryEntry,
		arg.ID,
		arg.FoodID,
		arg.AmountConsumed,
		arg.ConsumedAt,
		arg.MealType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
