// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, description, serving_size, serving_unit)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, serving_size, serving_unit, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateFoodParams struct {
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	ServingSize pgtype.Numeric `json:"serving_size"`
	ServingUnit string         `json:"serving_unit"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Description,
		arg.ServingSize,
		arg.ServingUnit,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServingSize,
		&i.ServingUnit,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFood = `-- name: GetFood :one
SELECT id, name, description, serving_size, serving_unit, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at FROM foods WHERE id = $1
`

func (q *Queries) GetFood(ctx context.Context, id pgtype.UUID) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServingSize,
		&i.ServingUnit,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT
  f.id,
  f.name,
  f.description,
  f.serving_size,
  f.serving_unit,
  COALESCE(MAX(fn.amount) FILTER (WHERE n.name = 'Caloric Value'), 0)::float AS calories,
  COALESCE(MAX(fn.amount) FILTER (WHERE n.name = 'Protein'), 0)::float AS protein,
  COALESCE(MAX(fn.amount) FILTER (WHERE n.name = 'Fat'), 0)::float AS fat,
  COALESCE(MAX(fn.amount) FILTER (WHERE n.name = 'Carbohydrates'), 0)::float AS carbs
FROM foods f
LEFT JOIN food_nutrients fn ON f.id = fn.food_id
LEFT JOIN nutrients n ON fn.nutrient_id = n.id
WHERE f.name ILIKE '%' || $3::text || '%'
GROUP BY f.id
ORDER BY f.name
LIMIT $1 OFFSET $2
`

type ListFoodsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Name   string `json:"name"`
}

type ListFoodsRow struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	ServingSize pgtype.Numeric `json:"serving_size"`
	ServingUnit string         `json:"serving_unit"`
	Calories    float64        `json:"calories"`
	Protein     float64        `json:"protein"`
	Fat         float64        `json:"fat"`
	Carbs       float64        `json:"carbs"`
}

func (q *Queries) ListFoods(ctx context.Context, arg ListFoodsParams) ([]ListFoodsRow, error) {
	rows, err := q.db.Query(ctx, listFoods, arg.Limit, arg.Offset, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoodsRow
	for rows.Next() {
		var i ListFoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ServingSize,
			&i.ServingUnit,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
