// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO nutrition_goals (user_id, daily_target_calories, start_date, end_date, goal_type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, created_at, updated_at
`

type CreateGoalParams struct {
	UserID              int64          `json:"user_id"`
	DailyTargetCalories pgtype.Numeric `json:"daily_target_calories"`
	StartDate           time.Time      `json:"start_date"`
	EndDate             pgtype.Date    `json:"end_date"`
	GoalType            string         `json:"goal_type"`
}

type CreateGoalRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (CreateGoalRow, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.DailyTargetCalories,
		arg.StartDate,
		arg.EndDate,
		arg.GoalType,
	)
	var i CreateGoalRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :execrows
UPDATE nutrition_goals
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteGoal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveGoalByUser = `-- name: GetActiveGoalByUser :one
SELECT id, user_id, daily_target_calories, start_date, end_date, goal_type, created_at, updated_at, deleted_at
FROM nutrition_goals
WHERE user_id = $1 
    AND start_date <= $2
    AND (end_date IS NULL OR end_date >= $2)
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveGoalByUserParams struct {
	UserID    int64     `json:"user_id"`
	StartDate time.Time `json:"start_date"`
}

func (q *Queries) GetActiveGoalByUser(ctx context.Context, arg GetActiveGoalByUserParams) (NutritionGoal, error) {
	row := q.db.QueryRow(ctx, getActiveGoalByUser, arg.UserID, arg.StartDate)
	var i NutritionGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyTargetCalories,
		&i.StartDate,
		&i.EndDate,
		&i.GoalType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllGoalsByUser = `-- name: GetAllGoalsByUser :many
SELECT id, user_id, daily_target_calories, start_date, end_date, goal_type, created_at, updated_at, deleted_at
FROM nutrition_goals
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllGoalsByUser(ctx context.Context, userID int64) ([]NutritionGoal, error) {
	rows, err := q.db.Query(ctx, getAllGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NutritionGoal
	for rows.Next() {
		var i NutritionGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DailyTargetCalories,
			&i.StartDate,
			&i.EndDate,
			&i.GoalType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, user_id, daily_target_calories, start_date, end_date, goal_type, created_at, updated_at, deleted_at
FROM nutrition_goals
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGoalByID(ctx context.Context, id int64) (NutritionGoal, error) {
	row := q.db.QueryRow(ctx, getGoalByID, id)
	var i NutritionGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyTargetCalories,
		&i.StartDate,
		&i.EndDate,
		&i.GoalType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoalsByUserAndDateRange = `-- name: GetGoalsByUserAndDateRange :many
SELECT id, user_id, daily_target_calories, start_date, end_date, goal_type, created_at, updated_at, deleted_at
FROM nutrition_goals
WHERE user_id = $1 
    AND start_date <= $2
    AND (end_date IS NULL OR end_date >= $1)
    AND deleted_at IS NULL
ORDER BY start_date DESC
`

type GetGoalsByUserAndDateRangeParams struct {
	UserID    int64     `json:"user_id"`
	StartDate time.Time `json:"start_date"`
}

func (q *Queries) GetGoalsByUserAndDateRange(ctx context.Context, arg GetGoalsByUserAndDateRangeParams) ([]NutritionGoal, error) {
	rows, err := q.db.Query(ctx, getGoalsByUserAndDateRange, arg.UserID, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NutritionGoal
	for rows.Next() {
		var i NutritionGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DailyTargetCalories,
			&i.StartDate,
			&i.EndDate,
			&i.GoalType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :execrows
UPDATE nutrition_goals
SET daily_target_calories = $1, start_date = $2, end_date = $3, goal_type = $4, updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateGoalParams struct {
	DailyTargetCalories pgtype.Numeric `json:"daily_target_calories"`
	StartDate           time.Time      `json:"start_date"`
	EndDate             pgtype.Date    `json:"end_date"`
	GoalType            string         `json:"goal_type"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGoal,
		arg.DailyTargetCalories,
		arg.StartDate,
		arg.EndDate,
		arg.GoalType,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
