// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLevelType string

const (
	ActivityLevelTypeSedentary  ActivityLevelType = "sedentary"
	ActivityLevelTypeLight      ActivityLevelType = "light"
	ActivityLevelTypeModerate   ActivityLevelType = "moderate"
	ActivityLevelTypeActive     ActivityLevelType = "active"
	ActivityLevelTypeVeryActive ActivityLevelType = "very_active"
)

func (e *ActivityLevelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityLevelType(s)
	case string:
		*e = ActivityLevelType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityLevelType: %T", src)
	}
	return nil
}

type NullActivityLevelType struct {
	ActivityLevelType ActivityLevelType
	Valid             bool // Valid is true if ActivityLevelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityLevelType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityLevelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityLevelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityLevelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityLevelType), nil
}

type ScanStatus string

const (
	ScanStatusPending    ScanStatus = "pending"
	ScanStatusProcessing ScanStatus = "processing"
	ScanStatusCompleted  ScanStatus = "completed"
	ScanStatusFailed     ScanStatus = "failed"
)

func (e *ScanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatus(s)
	case string:
		*e = ScanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatus: %T", src)
	}
	return nil
}

type NullScanStatus struct {
	ScanStatus ScanStatus
	Valid      bool // Valid is true if ScanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatus), nil
}

type UserGender string

const (
	UserGenderMale   UserGender = "male"
	UserGenderFemale UserGender = "female"
)

func (e *UserGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserGender(s)
	case string:
		*e = UserGender(s)
	default:
		return fmt.Errorf("unsupported scan type for UserGender: %T", src)
	}
	return nil
}

type NullUserGender struct {
	UserGender UserGender
	Valid      bool // Valid is true if UserGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserGender) Scan(value interface{}) error {
	if value == nil {
		ns.UserGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserGender), nil
}

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleAdmin      UserRole = "admin"
	UserRoleSuperAdmin UserRole = "super_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type NutritionLog struct {
	ID        pgtype.UUID
	FoodName  string
	Calories  pgtype.Numeric
	ProteinG  pgtype.Numeric
	CarbsG    pgtype.Numeric
	FatG      pgtype.Numeric
	SugarG    pgtype.Numeric
	UserID    pgtype.UUID
	ScanID    pgtype.UUID
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	DeletedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Profile struct {
	ID            pgtype.UUID
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DateOfBirth   pgtype.Date
	Weight        pgtype.Numeric
	Height        pgtype.Numeric
	Gender        NullUserGender
	ActivityLevel NullActivityLevelType
	UserID        pgtype.UUID
	CreatedBy     pgtype.UUID
	UpdatedBy     pgtype.UUID
	DeletedBy     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type ScanHistory struct {
	ID           pgtype.UUID
	ImgUrl       string
	Status       NullScanStatus
	ErrorMessage pgtype.Text
	UserID       pgtype.UUID
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	Role         NullUserRole
	PasswordHash string
	VerifiedAt   pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
