// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ScanStatus string

const (
	ScanStatusPending    ScanStatus = "pending"
	ScanStatusProcessing ScanStatus = "processing"
	ScanStatusCompleted  ScanStatus = "completed"
	ScanStatusFailed     ScanStatus = "failed"
)

func (e *ScanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatus(s)
	case string:
		*e = ScanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatus: %T", src)
	}
	return nil
}

type NullScanStatus struct {
	ScanStatus ScanStatus `json:"scan_status"`
	Valid      bool       `json:"valid"` // Valid is true if ScanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatus), nil
}

type AuditLog struct {
	ID           int64            `json:"id"`
	UserID       int64            `json:"user_id"`
	Action       string           `json:"action"`
	ResourceType string           `json:"resource_type"`
	ResourceID   pgtype.Int8      `json:"resource_id"`
	OldValue     []byte           `json:"old_value"`
	NewValue     []byte           `json:"new_value"`
	IpAddress    *netip.Addr      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Food struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ServingSize pgtype.Numeric     `json:"serving_size"`
	ServingUnit string             `json:"serving_unit"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type FoodDiary struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	FoodID         int64              `json:"food_id"`
	AmountConsumed pgtype.Numeric     `json:"amount_consumed"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	MealType       pgtype.Text        `json:"meal_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type FoodNutrient struct {
	FoodID     int64          `json:"food_id"`
	NutrientID int64          `json:"nutrient_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

type Nutrient struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Unit string `json:"unit"`
}

type NutritionGoal struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	DailyTargetCalories pgtype.Numeric     `json:"daily_target_calories"`
	StartDate           time.Time          `json:"start_date"`
	EndDate             pgtype.Date        `json:"end_date"`
	GoalType            string             `json:"goal_type"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type ScanHistory struct {
	ID            pgtype.UUID        `json:"id"`
	ImgUrl        string             `json:"img_url"`
	Status        NullScanStatus     `json:"status"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	UserID        int64              `json:"user_id"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	UpdatedBy     pgtype.Int8        `json:"updated_by"`
	DeletedBy     pgtype.Int8        `json:"deleted_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	NutritionData []byte             `json:"nutrition_data"`
}

type User struct {
	ID            int64              `json:"id"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	Password      []byte             `json:"password"`
	Height        pgtype.Numeric     `json:"height"`
	Weight        pgtype.Numeric     `json:"weight"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	ActivityLevel pgtype.Int4        `json:"activity_level"`
	Gender        pgtype.Text        `json:"gender"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	Avatar        pgtype.Text        `json:"avatar"`
	OtpSecret     pgtype.Text        `json:"otp_secret"`
	OtpEnabled    bool               `json:"otp_enabled"`
}
