// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutrition.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNutritionLog = `-- name: CreateNutritionLog :one
INSERT INTO nutrition_logs (
    food_name,
    calories,
    protein_g,
    carbs_g,
    fat_g,
    sugar_g,
    user_id,
    scan_id,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
  id,
  food_name,
  calories,
  protein_g,
  carbs_g,
  fat_g,
  sugar_g,
  user_id,
  scan_id,
  created_at
`

type CreateNutritionLogParams struct {
	FoodName  string         `json:"food_name"`
	Calories  pgtype.Numeric `json:"calories"`
	ProteinG  pgtype.Numeric `json:"protein_g"`
	CarbsG    pgtype.Numeric `json:"carbs_g"`
	FatG      pgtype.Numeric `json:"fat_g"`
	SugarG    pgtype.Numeric `json:"sugar_g"`
	UserID    pgtype.UUID    `json:"user_id"`
	ScanID    pgtype.UUID    `json:"scan_id"`
	CreatedBy pgtype.UUID    `json:"created_by"`
}

type CreateNutritionLogRow struct {
	ID        pgtype.UUID        `json:"id"`
	FoodName  string             `json:"food_name"`
	Calories  pgtype.Numeric     `json:"calories"`
	ProteinG  pgtype.Numeric     `json:"protein_g"`
	CarbsG    pgtype.Numeric     `json:"carbs_g"`
	FatG      pgtype.Numeric     `json:"fat_g"`
	SugarG    pgtype.Numeric     `json:"sugar_g"`
	UserID    pgtype.UUID        `json:"user_id"`
	ScanID    pgtype.UUID        `json:"scan_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateNutritionLog(ctx context.Context, arg CreateNutritionLogParams) (CreateNutritionLogRow, error) {
	row := q.db.QueryRow(ctx, createNutritionLog,
		arg.FoodName,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.UserID,
		arg.ScanID,
		arg.CreatedBy,
	)
	var i CreateNutritionLogRow
	err := row.Scan(
		&i.ID,
		&i.FoodName,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.SugarG,
		&i.UserID,
		&i.ScanID,
		&i.CreatedAt,
	)
	return i, err
}

type CreateNutritionLogsBatchParams struct {
	FoodName  string         `json:"food_name"`
	Calories  pgtype.Numeric `json:"calories"`
	ProteinG  pgtype.Numeric `json:"protein_g"`
	CarbsG    pgtype.Numeric `json:"carbs_g"`
	FatG      pgtype.Numeric `json:"fat_g"`
	SugarG    pgtype.Numeric `json:"sugar_g"`
	UserID    pgtype.UUID    `json:"user_id"`
	ScanID    pgtype.UUID    `json:"scan_id"`
	CreatedBy pgtype.UUID    `json:"created_by"`
}

const deleteNutritionLog = `-- name: DeleteNutritionLog :exec
UPDATE nutrition_logs
SET
  deleted_at = NOW(),
  deleted_by = $2,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteNutritionLogParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteNutritionLog(ctx context.Context, arg DeleteNutritionLogParams) error {
	_, err := q.db.Exec(ctx, deleteNutritionLog, arg.ID, arg.DeletedBy)
	return err
}

const updateNutritionLog = `-- name: UpdateNutritionLog :exec
UPDATE nutrition_logs
SET
  food_name = $2,
  calories = $3,
  protein_g = $4,
  carbs_g = $5,
  fat_g = $6,
  sugar_g = $7,
  updated_by = $8,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateNutritionLogParams struct {
	ID        pgtype.UUID    `json:"id"`
	FoodName  string         `json:"food_name"`
	Calories  pgtype.Numeric `json:"calories"`
	ProteinG  pgtype.Numeric `json:"protein_g"`
	CarbsG    pgtype.Numeric `json:"carbs_g"`
	FatG      pgtype.Numeric `json:"fat_g"`
	SugarG    pgtype.Numeric `json:"sugar_g"`
	UpdatedBy pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpdateNutritionLog(ctx context.Context, arg UpdateNutritionLogParams) error {
	_, err := q.db.Exec(ctx, updateNutritionLog,
		arg.ID,
		arg.FoodName,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.UpdatedBy,
	)
	return err
}
