// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
  user_id, first_name, last_name, date_of_birth, weight, height, gender, activity_level, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, first_name, last_name, date_of_birth, weight, height, gender, activity_level
`

type CreateProfileParams struct {
	UserID        pgtype.UUID
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DateOfBirth   pgtype.Date
	Weight        pgtype.Numeric
	Height        pgtype.Numeric
	Gender        NullUserGender
	ActivityLevel NullActivityLevelType
	CreatedBy     pgtype.UUID
}

type CreateProfileRow struct {
	ID            pgtype.UUID
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DateOfBirth   pgtype.Date
	Weight        pgtype.Numeric
	Height        pgtype.Numeric
	Gender        NullUserGender
	ActivityLevel NullActivityLevelType
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Weight,
		arg.Height,
		arg.Gender,
		arg.ActivityLevel,
		arg.CreatedBy,
	)
	var i CreateProfileRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Weight,
		&i.Height,
		&i.Gender,
		&i.ActivityLevel,
	)
	return i, err
}

const deleteProfileByUserId = `-- name: DeleteProfileByUserId :exec
UPDATE profiles
SET
  deleted_at = NOW(),
  deleted_by = $2,
  updated_at = NOW()
WHERE user_id = $1 AND deleted_at IS NULL
`

type DeleteProfileByUserIdParams struct {
	UserID    pgtype.UUID
	DeletedBy pgtype.UUID
}

func (q *Queries) DeleteProfileByUserId(ctx context.Context, arg DeleteProfileByUserIdParams) error {
	_, err := q.db.Exec(ctx, deleteProfileByUserId, arg.UserID, arg.DeletedBy)
	return err
}

const getProfileByUserId = `-- name: GetProfileByUserId :one
SELECT
  first_name,
  last_name,
  date_of_birth,
  weight,
  height,
  gender,
  activity_level,
  created_at
FROM profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetProfileByUserIdRow struct {
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DateOfBirth   pgtype.Date
	Weight        pgtype.Numeric
	Height        pgtype.Numeric
	Gender        NullUserGender
	ActivityLevel NullActivityLevelType
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetProfileByUserId(ctx context.Context, userID pgtype.UUID) (GetProfileByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserId, userID)
	var i GetProfileByUserIdRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Weight,
		&i.Height,
		&i.Gender,
		&i.ActivityLevel,
		&i.CreatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET
  first_name = $2,
  last_name = $3,
  date_of_birth = $4,
  weight = $5,
  height = $6,
  gender = $7,
  activity_level = $8,
  updated_by = $1,
  updated_at = NOW()
WHERE user_id = $1 AND deleted_at IS NULL
`

type UpdateProfileParams struct {
	UpdatedBy     pgtype.UUID
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DateOfBirth   pgtype.Date
	Weight        pgtype.Numeric
	Height        pgtype.Numeric
	Gender        NullUserGender
	ActivityLevel NullActivityLevelType
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.UpdatedBy,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Weight,
		arg.Height,
		arg.Gender,
		arg.ActivityLevel,
	)
	return err
}
