// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScanHistory = `-- name: CreateScanHistory :one
INSERT INTO scan_histories (
  img_url,
  user_id,
  created_by
) VALUES (
  $1, $2, $2
)
RETURNING id, img_url, status, error_message
`

type CreateScanHistoryParams struct {
	ImgUrl string
	UserID pgtype.UUID
}

type CreateScanHistoryRow struct {
	ID           pgtype.UUID
	ImgUrl       string
	Status       NullScanStatus
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateScanHistory(ctx context.Context, arg CreateScanHistoryParams) (CreateScanHistoryRow, error) {
	row := q.db.QueryRow(ctx, createScanHistory, arg.ImgUrl, arg.UserID)
	var i CreateScanHistoryRow
	err := row.Scan(
		&i.ID,
		&i.ImgUrl,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteScan = `-- name: DeleteScan :exec
UPDATE scan_histories
SET deleted_at = NOW(), deleted_by = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteScanParams struct {
	ID        pgtype.UUID
	DeletedBy pgtype.UUID
}

func (q *Queries) DeleteScan(ctx context.Context, arg DeleteScanParams) error {
	_, err := q.db.Exec(ctx, deleteScan, arg.ID, arg.DeletedBy)
	return err
}

const getScan = `-- name: GetScan :many
SELECT
  id,
  user_id,
  img_url,
  status,
  error_message,
  created_at
FROM scan_histories
WHERE deleted_at IS NULL
`

type GetScanRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ImgUrl       string
	Status       NullScanStatus
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetScan(ctx context.Context) ([]GetScanRow, error) {
	rows, err := q.db.Query(ctx, getScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScanRow
	for rows.Next() {
		var i GetScanRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImgUrl,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanById = `-- name: GetScanById :one
SELECT
  id,
  img_url,
  status,
  error_message,
  created_at
FROM scan_histories
WHERE id = $1 AND deleted_at IS NULL
`

type GetScanByIdRow struct {
	ID           pgtype.UUID
	ImgUrl       string
	Status       NullScanStatus
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetScanById(ctx context.Context, id pgtype.UUID) (GetScanByIdRow, error) {
	row := q.db.QueryRow(ctx, getScanById, id)
	var i GetScanByIdRow
	err := row.Scan(
		&i.ID,
		&i.ImgUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getScanByUserId = `-- name: GetScanByUserId :many
SELECT
  id,
  img_url,
  status,
  error_message,
  created_at
FROM scan_histories
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetScanByUserIdRow struct {
	ID           pgtype.UUID
	ImgUrl       string
	Status       NullScanStatus
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetScanByUserId(ctx context.Context, userID pgtype.UUID) ([]GetScanByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getScanByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScanByUserIdRow
	for rows.Next() {
		var i GetScanByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ImgUrl,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScan = `-- name: UpdateScan :exec
UPDATE scan_histories
SET status = $2, error_message = $3, updated_by = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateScanParams struct {
	ID           pgtype.UUID
	Status       NullScanStatus
	ErrorMessage pgtype.Text
	UpdatedBy    pgtype.UUID
}

func (q *Queries) UpdateScan(ctx context.Context, arg UpdateScanParams) error {
	_, err := q.db.Exec(ctx, updateScan,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedBy,
	)
	return err
}
