// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, old_value, new_value, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditLogParams struct {
	UserID       int64       `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Int8 `json:"resource_id"`
	OldValue     []byte      `json:"old_value"`
	NewValue     []byte      `json:"new_value"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OldValue,
		arg.NewValue,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const disable2FA = `-- name: Disable2FA :execrows
UPDATE users 
SET otp_secret = NULL, otp_enabled = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) Disable2FA(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, disable2FA, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enable2FA = `-- name: Enable2FA :execrows
UPDATE users 
SET otp_secret = $1, otp_enabled = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type Enable2FAParams struct {
	OtpSecret pgtype.Text `json:"otp_secret"`
	ID        int64       `json:"id"`
}

func (q *Queries) Enable2FA(ctx context.Context, arg Enable2FAParams) (int64, error) {
	result, err := q.db.Exec(ctx, enable2FA, arg.OtpSecret, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuditLogsByUserID = `-- name: GetAuditLogsByUserID :many
SELECT id, user_id, action, resource_type, resource_id, old_value, new_value, ip_address, user_agent, created_at
FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditLogsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAuditLogsByUserID(ctx context.Context, arg GetAuditLogsByUserIDParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValue,
			&i.NewValue,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
