// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password,
    email,
    height,
    weight,
    date_of_birth,
    activity_level,
    gender
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, created_at, updated_at
`

type CreateUserParams struct {
	Username      string         `json:"username"`
	Password      []byte         `json:"password"`
	Email         string         `json:"email"`
	Height        pgtype.Numeric `json:"height"`
	Weight        pgtype.Numeric `json:"weight"`
	DateOfBirth   pgtype.Date    `json:"date_of_birth"`
	ActivityLevel pgtype.Int4    `json:"activity_level"`
	Gender        pgtype.Text    `json:"gender"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Height,
		arg.Weight,
		arg.DateOfBirth,
		arg.ActivityLevel,
		arg.Gender,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT
    id,
    username,
    email,
    height,
    weight,
    date_of_birth,
    activity_level,
    gender,
    created_at,
    updated_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type GetAllUsersRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	Height        pgtype.Numeric     `json:"height"`
	Weight        pgtype.Numeric     `json:"weight"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	ActivityLevel pgtype.Int4        `json:"activity_level"`
	Gender        pgtype.Text        `json:"gender"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Height,
			&i.Weight,
			&i.DateOfBirth,
			&i.ActivityLevel,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedUsers = `-- name: GetPaginatedUsers :many
SELECT
    id,
    username,
    email,
    height,
    weight,
    date_of_birth,
    activity_level,
    gender,
    created_at,
    updated_at
FROM users
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type GetPaginatedUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPaginatedUsersRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	Height        pgtype.Numeric     `json:"height"`
	Weight        pgtype.Numeric     `json:"weight"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	ActivityLevel pgtype.Int4        `json:"activity_level"`
	Gender        pgtype.Text        `json:"gender"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPaginatedUsers(ctx context.Context, arg GetPaginatedUsersParams) ([]GetPaginatedUsersRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaginatedUsersRow
	for rows.Next() {
		var i GetPaginatedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Height,
			&i.Weight,
			&i.DateOfBirth,
			&i.ActivityLevel,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    username,
    password,
    email,
    weight,
    height,
    date_of_birth,
    activity_level,
    gender,
    created_at,
    updated_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	Password      []byte             `json:"password"`
	Email         string             `json:"email"`
	Weight        pgtype.Numeric     `json:"weight"`
	Height        pgtype.Numeric     `json:"height"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	ActivityLevel pgtype.Int4        `json:"activity_level"`
	Gender        pgtype.Text        `json:"gender"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Weight,
		&i.Height,
		&i.DateOfBirth,
		&i.ActivityLevel,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    email,
    height,
    weight,
    date_of_birth,
    activity_level,
    gender,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	Height        pgtype.Numeric     `json:"height"`
	Weight        pgtype.Numeric     `json:"weight"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	ActivityLevel pgtype.Int4        `json:"activity_level"`
	Gender        pgtype.Text        `json:"gender"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Height,
		&i.Weight,
		&i.DateOfBirth,
		&i.ActivityLevel,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET
    username = $2,
    email = $3,
    height = $4,
    weight = $5,
    date_of_birth = $6,
    activity_level = $7,
    gender = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID            int64          `json:"id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	Height        pgtype.Numeric `json:"height"`
	Weight        pgtype.Numeric `json:"weight"`
	DateOfBirth   pgtype.Date    `json:"date_of_birth"`
	ActivityLevel pgtype.Int4    `json:"activity_level"`
	Gender        pgtype.Text    `json:"gender"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Height,
		arg.Weight,
		arg.DateOfBirth,
		arg.ActivityLevel,
		arg.Gender,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :execrows
UPDATE users
SET
    avatar = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID     int64       `json:"id"`
	Avatar pgtype.Text `json:"avatar"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.Avatar)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET
    password = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password []byte `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
